### PR TITLE
Lex/api fetch loop

### PR DESCRIPTION
**Pull request by LPeterson18**
1. Added fetch calls for ethgasstation.info and etherchain.org
2. Added engine to fetch from APIs and add collected Ethereum fees (converted to Gwei) to db

### CODE REVIEW

**Review by thehobbit85 — CHANGES_REQUESTED** [review]
Instead of going one by one I'll just write it as a general point.
Every time you use "fetch", you should use cleaners for the result, and you should also try/catch and check for all types of response/server errors.

**Comment by thehobbit85** [comment]
Also, rebase this on top of the master and resolve conflicts.

**Comment by LPeterson18** [comment]
Rebased on top of main and resolved conflicts and updated according to conversation on Tuesday

**Review by thehobbit85 — CHANGES_REQUESTED** [review]
1. Change the data modal according to what was discussed in our meeting today:
 a. Change db name to "fee_{provider}".
 b. No need for provider name in the document.
 c. All the fee data should be inside a "data" object in the document.

2. Instead of pulling the data only from 1 location, pull it from all the providers using a "promise.all".

3. "Normalize" the dates by rounding them to nearest time in the interval.

**Comment by LPeterson18** [comment]
https://github.com/EdgeApp/edge-fee-tracker/pull/3
See new PR

**Pull request closed without merging**
