### PR TITLE
Lex/get data api endpoint

### PR DESCRIPTION
**Pull request by LPeterson18**
1. Added Endpoints to get data from db for:
     (a) ethgasstation.info
     (b) Mempool.space
     (c) bitcoinfees.earn.com

### CODE REVIEW

**Comment by LPeterson18** [comment]
get fee endpoint to bulk get all three providers at the same time, with start and end date as params

**Comment by LPeterson18** [comment]
Added endpoint to collect data from all three partners given two dates

**Comment by LPeterson18** [comment]
Changed helper function to use exit early

**Review by thehobbit85 — APPROVED** [review]

**Comment by LPeterson18** [comment]
Rebased to remove merge conflicts

**Review by thehobbit85 — APPROVED** [review]

**Pull request merged**
